### Preprocessing

In [30]:
import pandas as pd
import contractions
import spacy

from nltk.util import ngrams
from nltk.tokenize import word_tokenize

In [11]:
path = r"../data/raw/training.1600000.processed.noemoticon.csv"

data = pd.read_csv(path, encoding="latin1")

df = pd.DataFrame(data)

df.columns = ["Label", "Serial", "Date", "Query", "Twitter_id", "Tweet"]

In [12]:
df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [13]:
df["Clean_Text"] = df["Tweet"]

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@Kwesidei not the whole crew

### lowercase

In [14]:
df["Clean_Text"] = df["Tweet"].fillna("").astype(str).str.lower()

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@kenichan i dived many times for the ball. man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@kwesidei not the whole crew

### URL removal

In [15]:
pattern = r"https?://\S+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### mention removal

In [16]:
pattern = r"@\w+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### hashtag cleaning

In [17]:
pattern = r"#"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Punctuation removal

In [18]:
pattern = r"[!?_]"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Space cleaning

In [19]:

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    apply(lambda x: " ".join(x.split())))

### contractions

In [20]:
big_text = " ".join(df["Clean_Text"])

expanded_words = []

for word in big_text.split():
    expanded_words.append(contractions.fix(word))


big_text = " ".join(expanded_words)

In [21]:
tokens = word_tokenize(big_text)