### Preprocessing

In [42]:
import pandas as pd
import contractions
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [43]:
path = r"../data/raw/training.1600000.processed.noemoticon.csv"

data = pd.read_csv(path, encoding="latin1")

df = pd.DataFrame(data)

df.columns = ["Label", "Serial", "Date", "Query", "Twitter_id", "Tweet"]

In [44]:
df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [45]:
df["Clean_Text"] = df["Tweet"]

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@Kwesidei not the whole crew

### lowercase

In [46]:
df["Clean_Text"] = df["Tweet"].fillna("").astype(str).str.lower()

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@kenichan i dived many times for the ball. man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@kwesidei not the whole crew

Label

In [47]:
df.loc[df["Label"] == 4, "Label"] = 1

In [48]:
df.tail()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
1599994,1,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...,just woke up. having no school is the best fee...
1599995,1,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...,thewdb.com - very cool to hear old walt interv...
1599996,1,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...,are you ready for your mojo makeover? ask me f...
1599997,1,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...,happy 38th birthday to my boo of alll time!!! ...
1599998,1,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...,happy #charitytuesday @thenspcc @sparkscharity...

### URL removal

In [49]:
pattern = r"https?://\S+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### mention removal

In [50]:
pattern = r"@\w+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### hashtag cleaning

In [51]:
pattern = r"#"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Punctuation removal

In [52]:
pattern = r"[!?_]"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Space cleaning

In [53]:

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    apply(lambda x: " ".join(x.split())))

### contractions

In [54]:
df["Clean_Text"] = df["Clean_Text"].fillna("").astype(str).apply(
    lambda x: (contractions.fix(x))
)

In [55]:
df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to sa...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","no, it is not behaving at all. i am mad. why a..."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,not the whole crew

### Remove apostrophe

In [56]:
pattern = r"'s\b"

df["Clean_Text"] = df["Clean_Text"].astype(str).str.replace(pattern, "", regex=True)

### Tokenization

In [57]:
df["Tokens"] = df["Clean_Text"].fillna("").astype(str).apply(word_tokenize)

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text,Tokens
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...,"[is, upset, that, he, can, not, update, his, f..."
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to sa...,"[i, dived, many, times, for, the, ball, ., man..."
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire,"[my, whole, body, feels, itchy, and, like, its..."
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","no, it is not behaving at all. i am mad. why a...","[no, ,, it, is, not, behaving, at, all, ., i, ..."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,not the whole crew,"[not, the, whole, crew]"

### Stopwords cleaning

In [58]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parsa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [59]:
stop_words = set(stopwords.words("english"))

stop_words.discard("not")

df["Tokens"] = df["Tokens"].apply(
    lambda x: [word for word in x if word.lower() not in stop_words]
)

df["Clean_Text"] = df["Tokens"].apply(lambda x: " ".join(x))

In [60]:
df["Tokens"].sample(5)

1429807                       [well, hope, able, help, vent]
58749      [back, park, ., not, warm, looks, 1, lap, toda...
1008044    [boss, called, ., congratulate, ., repeat, :, ...
1453788    [sounds, good, fairly, hectic, couple, weeks, ...
1401951                       [shout, indonesia, god, bless]
Name: Tokens, dtype: object

In [61]:
df["Clean_Text"].sample(5)

814570     blood , action gore resident evil 2 ... time w...
1210655    says & quot ; pootle next two eggs nearly full...
1222787    thinking bbq lunch mmm nearly done crime essay...
38195      ahh think getting really dizzy , headache , st...
3628         got calm weekends monday blues carrying tuesday
Name: Clean_Text, dtype: str

### Final Conclution

In [62]:
df[["Tweet", "Clean_Text"]].sample(10)

,Tweet,Clean_Text
424319,@MAR7ENE hey my aunt works for playboy. She go...,hey aunt works playboy . goes lil parties & am...
884721,"Phone will be dead by 6am Pacific. I'm alive, ...","phone dead 6am pacific . alive , todd ."
104627,i dont know what i feel now,not know feel
244532,Havnt had a &quot;great/good day&quot; in a lo...,havnt & quot ; great/good day & quot ; long ti...
269197,"@reverz Tomorrow is going to suck or, excuse ...","tomorrow going suck , excuse , today ."
1518542,@stewartcutler there's always a first time,always first time
892155,Its My Birthday,birthday
378376,argh - work on a saturday,argh - work saturday
58722,needs more followers. HELP.,needs followers . help .
570413,I'm conducting a site health and safety inspec...,conducting site health safety inspection time ...

In [63]:
df.drop(["Tweet", "Query"], axis=1, inplace=True)

In [64]:
df.head()

,Label,Serial,Date,Twitter_id,Clean_Text,Tokens
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,upset not update facebook texting ... might cr...,"[upset, not, update, facebook, texting, ..., m..."
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,mattycus,dived many times ball . managed save 50 % rest...,"[dived, many, times, ball, ., managed, save, 5..."
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,whole body feels itchy like fire,"[whole, body, feels, itchy, like, fire]"
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,Karoli,", not behaving . mad . not see .","[,, not, behaving, ., mad, ., not, see, .]"
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,not whole crew,"[not, whole, crew]"

In [65]:
df.to_csv("../data/processed/cleaned_sentiment140.csv", index=False)