### Preprocessing

In [2]:
import pandas as pd
import contractions

from nltk.tokenize import word_tokenize

In [3]:
path = r"../data/raw/training.1600000.processed.noemoticon.csv"

data = pd.read_csv(path, encoding="latin1")

df = pd.DataFrame(data)

df.columns = ["Label", "Serial", "Date", "Query", "Twitter_id", "Tweet"]

In [4]:
df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [5]:
df["Clean_Text"] = df["Tweet"]

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@Kwesidei not the whole crew

### lowercase

In [6]:
df["Clean_Text"] = df["Tweet"].fillna("").astype(str).str.lower()

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@kenichan i dived many times for the ball. man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@kwesidei not the whole crew

### URL removal

In [7]:
pattern = r"https?://\S+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### mention removal

In [8]:
pattern = r"@\w+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### hashtag cleaning

In [9]:
pattern = r"#"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Punctuation removal

In [10]:
pattern = r"[!?_]"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Space cleaning

In [11]:

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    apply(lambda x: " ".join(x.split())))

### contractions

In [12]:
df["Clean_Text"] = df["Clean_Text"].fillna("").astype(str).apply(
    lambda x: (contractions.fix(x))
)

### Tokenization

In [13]:
df["Tokens"] = df["Clean_Text"].fillna("").astype(str).apply(word_tokenize)

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text,Tokens
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...,"[is, upset, that, he, can, not, update, his, f..."
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to sa...,"[i, dived, many, times, for, the, ball, ., man..."
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire,"[my, whole, body, feels, itchy, and, like, its..."
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","no, it is not behaving at all. i am mad. why a...","[no, ,, it, is, not, behaving, at, all, ., i, ..."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,not the whole crew,"[not, the, whole, crew]"

### Stopwords cleaning

In [16]:
stop_words = set(["is", "the", "if", "that", "at", "of", "a", "an", "it",
                  "to", "in", "on", "for", "with", "and", "or", "but"])

df["Tokens"] = df["Tokens"].apply(
    lambda x: [word for word in x if word not in stop_words]
)

In [17]:
df["Tokens"]

0          [upset, he, can, not, update, his, facebook, b...
1          [i, dived, many, times, ball, ., managed, save...
2           [my, whole, body, feels, itchy, like, its, fire]
3          [no, ,, not, behaving, all, ., i, am, mad, ., ...
4                                         [not, whole, crew]
                                 ...
1599994    [just, woke, up, ., having, no, school, best, ...
1599995    [thewdb.com, -, very, cool, hear, old, walt, i...
1599996    [are, you, ready, your, mojo, makeover, ask, m...
1599997    [happy, 38th, birthday, my, boo, alll, time, t...
1599998                              [happy, charitytuesday]
Name: Tokens, Length: 1599999, dtype: object

### Final Conclution

In [18]:
df[["Tweet", "Clean_Text"]].sample(10)

,Tweet,Clean_Text
1309366,@DanielaL Sounds exciting! On scooter it felt ...,sounds exciting on scooter it felt like being ...
527432,@realtin its not mine im looking for somethin...,its not mine i am looking for something like t...
1351119,@brooklynblondie thank you!!,thank you
687695,The problem with using a mac and an avi video ...,the problem with using a mac and an avi video ...
269099,"problem: need to keep studying, but brain is f...","problem: need to keep studying, but brain is f..."
445834,have installed Adobe Photoshop Album Starter E...,have installed adobe photoshop album starter e...
348508,Why is it raining!?,why is it raining
585545,can't stand these ups &amp; downs... I actuall...,cannot stand these ups &amp; downs... i actual...
165108,Been 2 years and m still devistated that they ...,been 2 years and m still devistated that they ...
505975,i'm sick..fault of sudden change of weather..s...,i am sick..fault of sudden change of weather.....

In [19]:
df.drop(["Tweet", "Query"], axis=1, inplace=True)

In [20]:
df.head()

,Label,Serial,Date,Twitter_id,Clean_Text,Tokens
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,is upset that he cannot update his facebook by...,"[upset, he, can, not, update, his, facebook, b..."
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,mattycus,i dived many times for the ball. managed to sa...,"[i, dived, many, times, ball, ., managed, save..."
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,my whole body feels itchy and like its on fire,"[my, whole, body, feels, itchy, like, its, fire]"
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,Karoli,"no, it is not behaving at all. i am mad. why a...","[no, ,, not, behaving, all, ., i, am, mad, ., ..."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,not the whole crew,"[not, whole, crew]"

In [21]:
df.to_csv("../data/processed/cleaned_sentiment140.csv", index=False)