### Preprocessing

In [21]:
import pandas as pd
import contractions
import spacy

from nltk.util import ngrams
from nltk.tokenize import word_tokenize

In [22]:
path = r"../data/raw/training.1600000.processed.noemoticon.csv"

data = pd.read_csv(path, encoding="latin1")

df = pd.DataFrame(data)

df.columns = ["Label", "Serial", "Date", "Query", "Twitter_id", "Tweet"]

In [23]:
df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [24]:
df["Clean_Text"] = df["Tweet"]

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@Kwesidei not the whole crew

### lowercase

In [25]:
df["Clean_Text"] = df["Tweet"].fillna("").astype(str).str.lower()

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@kenichan i dived many times for the ball. man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@kwesidei not the whole crew

### URL removal

In [26]:
pattern = r"https?://\S+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### mention removal

In [27]:
pattern = r"@\w+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### hashtag cleaning

In [28]:
pattern = r"#"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Punctuation removal

In [29]:
pattern = r"[!?_]"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Space cleaning

In [30]:

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    apply(lambda x: " ".join(x.split())))

### contractions

In [31]:
big_text = " ".join(df["Clean_Text"])

expanded_words = []

for word in big_text.split():
    expanded_words.append(contractions.fix(word))


big_text = " ".join(expanded_words)

In [32]:
tokens = word_tokenize(big_text)

### Final Conclution

In [33]:
df[["Tweet", "Clean_Text"]].sample(10)

,Tweet,Clean_Text
309083,'s stomach hurts,'s stomach hurts
551440,The sun is shining and I'm ill in bed *wohoo*,the sun is shining and i'm ill in bed *wohoo*
1213793,says hi. hello. Goodafternoon.. http://plurk....,says hi. hello. goodafternoon..
306337,"Awww, I wanna talk to him but he has projects ...","awww, i wanna talk to him but he has projects ..."
1084037,@plushoff that's my fav dip,that's my fav dip
1282799,"At work, cloudy 21Â°C....","at work, cloudy 21â°c...."
1210587,@shutupmeg haha nice,haha nice
858822,@patient_warrior did I send you wrong state......,did i send you wrong state...no he was in mn-m...
1224751,"Well, it is yet another Monday morning...(grum...","well, it is yet another monday morning...(grum..."
40250,Just got home from house hunting. Not much ou...,just got home from house hunting. not much out...

In [34]:
df.drop(["Tweet", "Query"], axis=1, inplace=True)

In [35]:
df.head()

,Label,Serial,Date,Twitter_id,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,is upset that he can't update his facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,mattycus,i dived many times for the ball. managed to sa...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,Karoli,"no, it's not behaving at all. i'm mad. why am ..."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,not the whole crew

In [36]:
df.to_csv("../data/processed/cleaned_sentiment140.csv", index=False)