### Preprocessing

In [1]:
import pandas as pd
import contractions
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
path = r"../data/raw/training.1600000.processed.noemoticon.csv"

data = pd.read_csv(path, encoding="latin1")

df = pd.DataFrame(data)

df.columns = ["Label", "Serial", "Date", "Query", "Twitter_id", "Tweet"]

In [3]:
df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [4]:
df["Clean_Text"] = df["Tweet"]

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@Kwesidei not the whole crew

### lowercase

In [5]:
df["Clean_Text"] = df["Tweet"].fillna("").astype(str).str.lower()

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,@kenichan i dived many times for the ball. man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,@kwesidei not the whole crew

Label

In [6]:
df.loc[df["Label"] == 4, "Label"] = 1

In [7]:
df.tail()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text
1599994,1,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...,just woke up. having no school is the best fee...
1599995,1,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...,thewdb.com - very cool to hear old walt interv...
1599996,1,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...,are you ready for your mojo makeover? ask me f...
1599997,1,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...,happy 38th birthday to my boo of alll time!!! ...
1599998,1,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...,happy #charitytuesday @thenspcc @sparkscharity...

### URL removal

In [8]:
pattern = r"https?://\S+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### mention removal

In [9]:
pattern = r"@\w+"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### hashtag cleaning

In [10]:
pattern = r"#"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Punctuation removal

In [11]:
pattern = r"[!?_]"

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    str.replace(pattern, "", regex=True))

### Space cleaning

In [12]:

df["Clean_Text"] = (df["Clean_Text"].fillna("").astype(str).
                    apply(lambda x: " ".join(x.split())))

### contractions

In [13]:
df["Clean_Text"] = df["Clean_Text"].fillna("").astype(str).apply(
    lambda x: (contractions.fix(x))
)

### Tokenization

In [14]:
df["Tokens"] = df["Clean_Text"].fillna("").astype(str).apply(word_tokenize)

df.head()

,Label,Serial,Date,Query,Twitter_id,Tweet,Clean_Text,Tokens
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...,"[is, upset, that, he, can, not, update, his, f..."
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to sa...,"[i, dived, many, times, for, the, ball, ., man..."
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire,"[my, whole, body, feels, itchy, and, like, its..."
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","no, it is not behaving at all. i am mad. why a...","[no, ,, it, is, not, behaving, at, all, ., i, ..."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew,not the whole crew,"[not, the, whole, crew]"

### Stopwords cleaning

In [16]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parsa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [17]:
stop_words = set(stopwords.words("english"))

stop_words.discard("not")

df["Tokens"] = df["Tokens"].apply(
    lambda x: [word for word in x if word.lower() not in stop_words]
)

df["Clean_Text"] = df["Tokens"].apply(lambda x: " ".join(x))

In [18]:
df["Tokens"].sample(5)

944004     [someone, told, &, quot, ;, 7things, climb, &,...
1196356            [yum, jealous, &, amp, ;, craving, sushi]
784768     [tired, ,, hungry, like, half, seven, ,, cba, ...
648132     [synced, tvshows, istore, touch, not, find, .,...
1361783    [sicid, rite, .., wrote, back, ..., neva, tlk,...
Name: Tokens, dtype: object

In [19]:
df["Clean_Text"].sample(5)

1293646    back school .. loves project week ... totally ...
1347214       home work , deciding tonight . going eat first
39287                 hate whenever rains heavily home alone
634206     lil bro got clean break left forearm skating y...
193230     sunniest saturday far working day saturdays ba...
Name: Clean_Text, dtype: str

### Final Conclution

In [20]:
df[["Tweet", "Clean_Text"]].sample(10)

,Tweet,Clean_Text
574722,In the batcave Grad School sucks.... !,batcave grad school sucks ....
1377341,I'm home studying on a Friday night for my fin...,home studying friday night final tomorrow ... ...
816259,man so board. Im going to play guitar hero.,man board . going play guitar hero .
1203443,"@schillingfan You're pushing it, Missy. Howeve...","pushing , missy . however , try dig sparkly sh..."
1088774,fuk you word limit...to be honest no one likes...,fuk word limit ... honest one likes
696417,everything's going wrong today,everything 's going wrong today
807392,should be getting her passport interview done ...,getting passport interview done tomorrow .
124516,this makes me so angry =&gt; http://bit.ly/SgV...,"makes angry = & gt ; dumbarse truckie , poor a..."
369461,@jima6636 you mad at me ?,mad
1539061,@Enjoem Feels a lot better. I was flushing it...,feels lot better . flushing regularly keep lub...

In [21]:
df.drop(["Tweet", "Query"], axis=1, inplace=True)

In [22]:
df.head()

,Label,Serial,Date,Twitter_id,Clean_Text,Tokens
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,upset not update facebook texting ... might cr...,"[upset, not, update, facebook, texting, ..., m..."
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,mattycus,dived many times ball . managed save 50 % rest...,"[dived, many, times, ball, ., managed, save, 5..."
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,whole body feels itchy like fire,"[whole, body, feels, itchy, like, fire]"
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,Karoli,", not behaving . mad . not see .","[,, not, behaving, ., mad, ., not, see, .]"
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,not whole crew,"[not, whole, crew]"

In [23]:
df.to_csv("../data/processed/cleaned_sentiment140.csv", index=False)